- name: Deploy Users on Linux
  hosts: linux
  become: true
  tasks:

    - name: Create devops group
      ansible.builtin.group:
        name: devops
        state: present

    - name: Create devops user
      ansible.builtin.user:
        name: devopsuser
        group: devops
        shell: /bin/bash
        create_home: true
        state: present

    - name: Add devopsuser to sudoers
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/devopsuser
        line: 'devopsuser ALL=(ALL) NOPASSWD:ALL'
        create: true
        mode: '0440'
