name: Ansible Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Install Ansible and lint
        run: pip install ansible ansible-lint

      - name: Install required collections
        run: |
          ansible-galaxy collection install community.general
          ansible-galaxy collection install ansible.windows
          ansible-galaxy collection install community.windows
          ansible-galaxy collection install chocolatey.chocolatey

      - name: Run ansible-lint
        run: ansible-lint playbooks/linux-hardening.yml playbooks/deploy-users.yml
